version: "3"
services:
  # web:
  #   build: ./server
  #   command: flask run -h 0.0.0.0
  #   ports:
  #     - 5000:5000
  #   env_file:
  #     - ./.env.dev
  db:
    image: "postgres:alpine"
    container_name: "postgres-0"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password